<?php

/**
 * @file
 * Primary module hooks for Bootstrap flag icons module.
 */

use Drupal\Component\Utility\NestedArray;

/**
 * Implements hook_theme().
 */
function bootstrap_flag_icons_theme($existing, $type, $theme, $path) {
  return [
    'links__bootstrap_flag_icons_block' => ['base hook' => 'links'],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Preprocess for links--bootstrap-flag-icons-block.html.twig.
 */
function bootstrap_flag_icons_preprocess_links__bootstrap_flag_icons_block(&$vars) {
  $vars['current_language'] = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $vars['languages'] = [];
  foreach ($vars['links'] as $lang_key => $link) {
    /** @var \Drupal\Core\Url $url */
    $url = $link['link']['#url'];
    $url_options = NestedArray::mergeDeep($url->getOptions(), $link['link']['#options']);
    $vars['languages'][$lang_key]['url'] = $url->setOptions($url_options);
    if (!empty($link['link']['#options']['attributes'])) {
      if ($link['link']['#options']['attributes']['data-mode'] != 'icons') {
        $vars['languages'][$lang_key]['title'] = t('@link', ['@link' => $link["text"]]);
      }
    }
  }
}
